[lcspirit-977]- Azimuth on marker
cospirit/map-component pull request #6
Opened 2024-03-12 16:57 UTC by doninj

Adding a function to add an icon showing the direction with the panel's azimuth

2024-03-13 16:28 UTC, Jagagon approved these changes

2024-03-13 16:31 UTC, Jagagon commented on utils/Marker.ts
> +    public static getCustomMarkerSvgCodeWithAzimuth(color: string, azimuth: number, width: number = 24, height: number = 24, anchorPosition: Anchor = "bottom-center"): L.DivIcon {
N'était-ce pas plus joli de factoriser avec la méthode getCustomMarkerSvgCode en ajoutant un dernier paramètre optionnel azimuth: number|null et gérer les 2 modifs (innerHtml + svgCode) ?

2024-03-14 13:41 UTC, lotholf approved these changes

2024-03-15 08:29 UTC, Puillet approved these changes

2024-03-20 11:10 UTC, jbdz requested changes

2024-03-20 11:10 UTC, jbdz commented on utils/Marker.ts
> +        }
Le else est inutile ici vu qu'il y a un return dans le premier if

2024-03-20 16:52 UTC, jbdz approved these changes

2024-03-26 08:59 UTC, merged